name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: make build
    - name: Upload
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Linux
        path: ./bin/themesw
